--- 
- name: '[EL] create users on the server'
  user:
    name: "{{ item.os_user_name }}"
    shell: '/bin/bash'
    uid: "{{ item.os_user_guid | default( omit, true) }}"
    state: present
    groups: adm,wheel,systemd-journal
  with_items: "{{ os_users }}"
  when: ansible_os_family == "RedHat" 

- name: '[Ubuntu] Create users on the server'
  user:
    name: "{{ item.os_user_name }}"
    shell: '/bin/bash'
    uid: '{{ item.os_user_guid | default( omit, true ) }}'
    state: present
  with_items: "{{ os_users }}"
  when: ansible_os_family == "Debian"

- debug:
    msg: "{{ item.os_user_add_to_sudoers }}"

- name: 'User rules for {{ os_users.os_user_name }}'
  lineinfile:
    dest: '/etc/sudoers'
    state: present
    line: '{{ item.os_user_name }} ALL=(ALL) NOPASSWD:ALL'
    insertafter: EOF
  with_items: "{{ os_users }}"
  when:
    -  item.os_user_add_to_sudoers is defined
    -  item.os_user_add_to_sudoers is bool
