--- 
- name: '[EL] create users on the server'
  user:
    name: "{{ item.os_user_name }}"
    shell: '/bin/bash'
    uid: "{{ item.os_user_guid | default( omit, true) }}"
    state: present
    groups: adm,wheel,systemd-journal
  with_items: "{{ os_users }}"
  when: ansible_os_family == "RedHat" 

- name: '[Ubuntu] Create users on the server'
  user:
    name: "{{ item.os_user_name }}"
    shell: '/bin/bash'
    uid: '{{ item.os_user_guid | default( omit, true ) }}'
    state: present
  with_items: "{{ os_users }}"
  when: ansible_os_family == "Debian"
